apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-processing
  template:
    metadata:
      labels:
        app: activity-processing
    spec:
      containers:
      - name: activity-processing
        image: hassan196/activityprocessingservice:v2  # updated image
        env:
          - name: KAFKA_BROKER
            value: "kafka:9092"
          - name: KAFKA_TOPIC_ID
            value: "activity-logs"
          - name: MONGO_URI          # use uppercase for environment variable
            value: MONGO_URI
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: activity-processing
spec:
  type: ClusterIP
  selector:
    app: activity-processing
  ports:
    - port: 3000
      targetPort: 3000
