apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-query
  template:
    metadata:
      labels:
        app: activity-query
    spec:
      containers:
      - name: activity-query
        image: hassan196/activityqueryservice:v2
        env:
          - name: PORT
            value: "3000"
          - name: mongo-uri
            value: MONGO_URI
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: activity-query
spec:
  type: LoadBalancer
  selector:
    app: activity-query
  ports:
    - port: 3000
      targetPort: 3000
